### ISSUE TITLE
Descargar web

### ISSUE THREAD

**Issue by 10000585** [bicimarketlostfound/lost-found#2]
Tenemos que descargar la página web de http://www.bicimarket.com/ para poder agregar la parte del proyecto

**Comment by 10000585** [comment]
Seguimos teniendo problemas con la descarga de la web.

**Comment by su6zero** [comment]
Finalmente hemos modificado el base de los documentos que tenemos en local, de este modo seguimos utilizando los recursos del servidor de la web, mientras trabajamos con nuestro código local.
