### ISSUE TITLE
Incidencia en la descarga

### ISSUE THREAD

**Issue by 10000585** [bicimarketlostfound/lost-found#6]
En primer lugar hemos intentado descargar la página con HTTrack y nos ha dado error por protecciones varias.

**Comment by su6zero** [comment]
Hemos empleado el programa inspyder, que requiere una licencia de pago, y aún que nos ha logrado extraer la totalidad de la página, nos solicita pagar la licencia para poder acceder a los datos.

Tenemos que replantearnos la posibilidad de no extraer la web en su totalidad.

**Comment by su6zero** [comment]
Finalmente hemos modificado el base del documento html, por lo que tenemos el html en local, y todos los scripts, hojas de estilos, imágenes y demás permanecen en su servidor original.
