### ISSUE TITLE
Estudio competencia

### ISSUE THREAD

**Issue by 10000585** [bicimarketlostfound/lost-found#8]
Realizaremos búsqueda de otras webs dedicadas a bicicletas robadas/perdidas
*Web de los mossos de esquadra_según noticia 2014 tiene un buscador (no lo hemos encontrado)
*http://www.redciclista.com/bicicletas/robadas/
*https://www.biciregistro.es/esp/buscador.php?bici_desaparecida=on
*https://www.facebook.com/Bicicletas-Robadas-191327980915114/
*https://www.bttbike.com/robo/

**Comment by su6zero** [comment]
Hemos determinado cómo enfocaremos el servicio, además de haber solucionado la duda que teníamos respecto a las bicicletas sin número de serie, que finalmente se mostrarán siempre que no haya coincidencias con los otros criterios de búsqueda.

**Comment by su6zero** [comment]
Hemos determinado cómo enfocaremos el servicio, además de haber solucionado la duda que teníamos respecto a las bicicletas sin número de serie, que finalmente se mostrarán siempre que no haya coincidencias con los otros criterios de búsqueda.
