### ISSUE TITLE
Registros bd

### ISSUE THREAD

**Issue by 10000585** [bicimarketlostfound/lost-found#9]
Creación de un excel con los registros a introducir en la base de datos. Se crea el excel para poder transformar en csv el documento y convertir después en texto con las ' ' para substituir en la sentencia sql de forma rápida y efectiva sin perder ni la consulta ni los datos.

**Comment by su6zero** [comment]
Excel realizado.

**Comment by su6zero** [comment]
Excel finalizado y extraído como .svc
